export const Genres =['Fiction',
'classique',
'Jeunesse',
'lecture aisée',
'lecture avancée',
'Documents et essais',
'Non-Fiction',
'correspondance',
'nouvelle',
'Documents - Essais',
'conte',
'lecture intermédiaire',
'Romans',
'Poésie',
'biographie',
'Romans - Fantastique & SF',
'Humour',
'Romans - Historique',
'poesie',
'théatre',
'Nouvelles - Contes Fantastique & SF',
'Fantastique',
'Fantastique & SF',
'Dictionnaire',
'Contes;Érotisme',
'Nouvelles - Contes Jeunesse']

export const Pays = ['France', 'Etats-Unis', 'Danemark', 'Canada', 'Angleterre', 'Espagne', 'Allemagne', 'Belgique', 'Russie', 'Irlande', 'Tchéquie'
,'Roumanie', 'Ukraine', 'Nouvelle-Zélande', 'Écosse', 'Autriche']

export const Continents = ['Europe', 'Amérique']

export const Annees = ['0101', '1880', '1899', '1898', '1813', '2011', '1857', '1860',
'1847', '1846', '1916', '1932', '1937', '1895', '1902', '1913',
'1883', '1888', '1927', '1924', '1925', '1926', '1933', '1935',
'1887', '1936', '1917', '1900', '1871', '1864', '1865', '1872',
'1934', '1876', '1867', '1874', '1858', '1868', '1878', '1866',
'1850', '1863', '1845', '1910', '2012', '1877', '1893', '1904',
'1909', '1908', '1892', '1873', '1862', '1869', '1928', '1922',
'1930', '1851', '1875', '1879', '1855', '1837', '1836', '1911',
'1809', '1839', '1882', '1885', '1884', '1881', '1890', '1891',
'1897', '1923', '1825', '1852', '1906', '1946', '1829', '2010',
'1824', '1819', '1894', '1896', '1812', '1886', '1844', '1918',
'1912', '1907', '1931', '1929', '1921', '1915', '1919', '1920',
'1914', '1796', '1903', '1978', '1901', '1870', '1889', '1830',
'1861', '1788', '1822', '1956', '1955', '1697', '1835', '1838',
'1843', '1841', '1849', '1832', '1856', '1840', '1833', '1842',
'2013', '1820', '1763']

export const Auteurs =['Edmond About', 'Amédée Achard', 'Paul Adam', 'Lucie des Ages',
'Gustave Aimard', 'Alain-Fournier', 'Louisa May Alcott',
'Alphonse Allais', 'Alphonse Allais - Tristan Bernard',
'Hans Christian Andersen', 'Claude Anet',
'Arène, Maupassant, Silvestre__', 'Paul Arène', "Boyer d'Argens",
'Olivar Asselin', 'Alfred Assollant', 'Marguerite Audoux',
"Marie Catherine d'Aulnoy", 'Jane Austen',
'Raymond Auzias-Turenne', 'Adolphe Badin', 'Honoré de Balzac',
'Charles Barbara', 'Jules Amédée Barbey d’Aurevilly',
'Henri Barbusse', 'Maurice Barrès', 'Robertine Barry (Françoise)',
'Charles Baudelaire', 'René Bazin', 'Honoré Beaugrand',
'Jeanne de Beaulieu', 'Jeanne-Marie Leprince de Beaumont',
'Sarah Bernhardt', 'Hector Berthelot', 'Arsène Bessette',
'Jean-François Bladé', 'Vicente Blasco-Ibanez',
'Vicente Blasco-Ibañez', 'Léon Bloy', 'Fortuné du Boisgobey',
'Henry Bordeaux', 'Georges Boucher de Boucherville',
'Jean-Nicolas Bouilly', 'Alain Bouissière', 'Napoléon Bourassa',
'Léon Bourgeois', 'Paul Bourget', 'Louis Boussenard',
'Eugène Boutmy', 'René Boylesve', 'Jean de La Brète',
'Anne Brontë', 'Charlotte Brontë', 'Emily Brontë', 'John Buchan',
'Charles Buet', 'Edward Bulwer-Lytton', 'Frances Hodgson Burnett',
'Jean-Baptiste Caouette', 'Zulma Carraud', 'Jacques Cazotte',
'Adelbert von Chamisso', 'H. de Chavannes de la Giraudière',
'Victor Cherbuliez', 'H.-Émile Chevalier', 'Ernest Choquette',
'Albert Cim', 'Sylva Clapin', 'Wilkie Collins', 'Laure Conan',
'Henri Conscience', 'Benjamin Constant', 'Fred et Coolmicro',
'James Fenimore Cooper', 'François Coppée', 'Georges Courteline',
'René Crevel', 'Eugène Dabit', 'Joséphine Dandurand',
'Alphonse Daudet', 'Ernest Daudet', 'Laurent-Olivier David',
'Delly', 'Robert Denoël', 'Charles Deslys',
'Wenceslas-Eugène Dick', 'Charles Dickens', 'Denis Diderot',
'Baschô et disciples', 'Roger Dombre', 'Fiodor Dostoïevski',
'Fyodor Dostoïevski', 'Joseph Doutre', 'Arthur Conan Doyle',
'Alexandre Dumas', 'Alexandre Dumas fils', 'Louis Dupire',
'Édouard Duquet', 'Georges Eekhoud', 'Marc Elder',
"Adolphe d'Ennery", 'Erckmann-Chatrian', 'Sheridan Le Fanu',
'Georges Le Faure', 'Octave Feuillet', 'Paul Féval',
'Aristide Filiatreault', 'Francis Scott Fitzgerald',
'Camille Flammarion', 'Gustave Flaubert', 'Daniel De Foe',
'Auguste Fortier', 'Jules Fournier', 'Anatole France',
'Louis Fréchette', 'Émile Gaboriau', 'Arnould Galopin',
'Louis Garneray', 'Elizabeth Gaskell',
'Philippe Aubert de Gaspé, fils', 'Philippe Aubert de Gaspé',
'Théophile Gautier', 'Antoine Gérin-Lajoie',
'Delphine de Girardin', 'Jules Girardin', 'Jean Giraudoux',
'Arthur Gobineau', 'Johann Wolfgang von Goethe', 'Nicolaï Gogol',
'Edmond et Jules de Goncourt', 'Henry Gréville',
'Jakob et Wilhelm Grimm', 'Charles de Guise', 'Gyp',
'Jaroslav Hasek', 'Wilhelm Hauff', 'Nathaniel Hawthorne',
'Louis Hémon', 'Madame Henri de la Ville de Mirmont', 'O. Henry',
'E.T.A. Hoffmann', 'Arsène Houssaye', 'Victor Hugo',
'R. P. Hugolin', 'Joris-Karl Huysmans', 'Washington Irving',
'Panaït Istrati', 'Paul d’Ivoi', 'Alfred Jarry', 'Franz Kafka',
'Rudyard Kipling', 'William Kirby', 'Ch. Paul de Kock',
'Vladimir Korolenko', "Eugène L'Écuyer", 'Albert Laberge',
'Édouard Laboulaye', 'Patrice Lacombe', 'André Lafon',
'Joseph Lallier', 'Hubert Larue', 'André Laurie',
'Le Comte de Lautréamont', 'Gaston Lavalley', 'Maurice Leblanc',
'Napoléon Legendre', 'Jules Lermina', 'Gaston Leroux',
'Maurice Level', 'Matthew Gregory Lewis', 'André Lichtenberger',
'Jack London', 'Albert Londres', 'Jean Aubert Loranger',
'Jean-Aubert Loranger', 'Pierre Loti', 'Pierre Louys',
'Howard Phillips Lovecraft', 'Albert Lozeau', 'Pierre Maël',
'Hector Malot', 'Katherine Mansfield', 'Jeanne Marcel',
'Paul Margueritte', 'Joseph Marmette', 'Karl Marx', 'Jules Mary',
'Guy de Maupassant', 'Pamphile Le May', 'Thomas Mayne-Reid',
'Didier Meral', 'Prosper Mérimée',
'Pauline de Meulan (Madame Guizot)', 'Louise Michel',
'Octave Mirbeau', 'Frédéric Mistral', 'Xavier de Montépin',
'Montesquieu', 'Joseph-Ferdinand Morissette', 'José Moselli',
'Émile Moselly', 'Eugène Muller', 'Dinah Maria Mulock',
'Henri Murger', 'John-Antoine Nau', 'Irène Némirovsky',
'Andréa de Nerciat', 'Charles Nodier', 'Georges Ohnet',
'Baronne Emmuska Orczy', 'Louis-Joseph Papineau',
'Charles Perrault', 'Edgar Allan Poe', 'Marcel Prévost',
'Pierre-Joseph Proudhon', 'Marcel Proust', 'Joseph Provost',
'Joseph Raîche', 'Hugues Rebell', 'Élisée Reclus', 'Jules Renard',
'Arthur Rimbaud', 'Romain Rolland', 'J.-H. Rosny Aîné',
'Edmond Rostand', 'Gustave Le Rouge', 'Eugène Le Roy', 'Han Ryner',
'Leopold Sacher-Masoch',
'Donatien Alphonse François Marquis de Sade',
'Antoine de Saint-Exupéry', 'Albert Samain', 'George Sand',
'Natesa Sastri', 'Johann Christopher Schmid', 'Marcel Schwob',
'Walter Scott', 'Comtesse de Ségur', 'Vladimir Soloviev',
'Stendhal', 'Bram Stoker', 'Émile Verhaeren', 'Paul Verlaine',
'Voltaire', 'Kazimierz Waliszewski', 'Émile Zola']